name: Testing output capture between steps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-that-output:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 
      - name: Produce json output
        id: my-output
        run: echo "::set-output name=version::$(cat sample-publish-output.json | jq .Version)"
      - name: Consume json output
        run: echo ${{ steps.my-output.outputs.version }}

  environment-extravaganza:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 
      - name: Set up the github env
        run: |
          echo "MY_VAR=GREAT" >> $GITHUB_ENV
      - name: Use the environment!
        run: echo ${{ env.MY_VAR }}

